MOROCCO_TERMS = [
    "المغرب",
    "المغربية",
    "مغربي",
    "مغاربة",
    "الرباط",
    "الدار البيضاء",
    "مراكش",
    "طنجة",
    "فاس",
    "أكادير",
    "الحكومة المغربية",
    "البرلمان المغربي",
    "المنتخب المغربي",
    "أسود الأطلس",
    "محمد السادس",
]

TRANSFER_TERMS = [
    "انتقال",
    "انتقالات",
    "صفقة",
    "توقيع",
    "يوقع",
    "وقع",
    "ضم",
    "إعارة",
    "مفاوضات",
    "اهتمام",
    "عرض",
    "عقد",
    "تجديد",
    "transfer",
    "transfers",
    "signing",
    "signed",
    "loan",
    "contract",
    "renewal",
    "negotiation",
    "interest",
    "offer",
]

MOROCCAN_PLAYERS = [
    "أشرف حكيمي",
    "Achraf Hakimi",
    "براهيم دياز",
    "Brahim Diaz",
    "يوسف النصيري",
    "Youssef En-Nesyri",
    "أيوب الكعبي",
    "Ayoub El Kaabi",
    "سفيان رحيمي",
    "Soufiane Rahimi",
    "نايف أكرد",
    "Nayef Aguerd",
    "عز الدين أوناحي",
    "Azzedine Ounahi",
    "حكيم زياش",
    "Hakim Ziyech",
    "سفيان أمرابط",
    "Sofyan Amrabat",
    "نصير مزراوي",
    "Noussair Mazraoui",
    "بلال الخنوس",
    "Bilal El Khannouss",
    "إلياس بن صغير",
    "Eliesse Ben Seghir",
    "عبد الصمد الزلزولي",
    "Abde Ezzalzouli",
    "أمين حارث",
    "Amine Harit",
    "ياسين بونو",
    "Yassine Bounou",
    "إسماعيل الصيباري",
    "Ismael Saibari",
    "رضا بلحيان",
    "Reda Belahyane",
    "أمين عدلي",
    "Amine Adli",
    "شادي رياض",
    "Chadi Riad",
    "إسماعيل قندوس",
    "Ismael Kandouss",
    "سليم أملاح",
    "Selim Amallah",
]


SOURCES = [

    # 🇲🇦 مصادر المغرب
    (
        "MAP عربي",
        "https://news.google.com/rss/search?q=site%3Amapnews.ma&hl=ar&gl=MA&ceid=MA%3Aar",
        "A",
        "morocco",
    ),
    (
        "SNRTnews عربي",
        "https://news.google.com/rss/search?q=site%3Asnrtnews.com&hl=ar&gl=MA&ceid=MA%3Aar",
        "A",
        "morocco",
    ),
    (
        "هسبريس",
        "https://news.google.com/rss/search?q=site%3Ahespress.com&hl=ar&gl=MA&ceid=MA%3Aar",
        "B",
        "morocco",
    ),
    (
        "Le360 عربي",
        "https://news.google.com/rss/search?q=site%3Aar.le360.ma&hl=ar&gl=MA&ceid=MA%3Aar",
        "B",
        "morocco",
    ),
    (
        "العمق المغربي",
        "https://news.google.com/rss/search?q=site%3Aal3omk.com&hl=ar&gl=MA&ceid=MA%3Aar",
        "B",
        "morocco",
    ),
    (
        "اليوم24",
        "https://news.google.com/rss/search?q=site%3Aalyaoum24.com&hl=ar&gl=MA&ceid=MA%3Aar",
        "B",
        "morocco",
    ),
    (
        "أخبارنا المغربية",
        "https://news.google.com/rss/search?q=site%3Aakhbarona.com&hl=ar&gl=MA&ceid=MA%3Aar",
        "B",
        "morocco",
    ),
    (
        "هبة بريس",
        "https://news.google.com/rss/search?q=site%3Ahibapress.com&hl=ar&gl=MA&ceid=MA%3Aar",
        "B",
        "morocco",
    ),
    (
        "برلمان",
        "https://news.google.com/rss/search?q=site%3Abarlamane.com&hl=ar&gl=MA&ceid=MA%3Aar",
        "B",
        "morocco",
    ),
    (
        "كود",
        "https://news.google.com/rss/search?q=site%3Agoud.ma&hl=ar&gl=MA&ceid=MA%3Aar",
        "B",
        "morocco",
    ),
    (
        "كفاش",
        "https://news.google.com/rss/search?q=site%3Akifache.com&hl=ar&gl=MA&ceid=MA%3Aar",
        "B",
        "morocco",
    ),
    (
        "فبراير",
        "https://news.google.com/rss/search?q=site%3Afebrayer.com&hl=ar&gl=MA&ceid=MA%3Aar",
        "B",
        "morocco",
    ),
    (
        "البطولة",
        "https://news.google.com/rss/search?q=site%3Aelbotola.com&hl=ar&gl=MA&ceid=MA%3Aar",
        "C",
        "morocco",
    ),
    (
        "المنتخب",
        "https://news.google.com/rss/search?q=site%3Aalmountakhab.com&hl=ar&gl=MA&ceid=MA%3Aar",
        "C",
        "morocco",
    ),

    # 🌍 الشرق الأوسط
    (
        "الجزيرة",
        "https://news.google.com/rss/search?q=site%3Aaljazeera.net&hl=ar&gl=MA&ceid=MA%3Aar",
        "A",
        "middle_east",
    ),
    (
        "العربية",
        "https://news.google.com/rss/search?q=site%3Aalarabiya.net&hl=ar&gl=MA&ceid=MA%3Aar",
        "A",
        "middle_east",
    ),
    (
        "سكاي نيوز عربية",
        "https://news.google.com/rss/search?q=site%3Askynewsarabia.com&hl=ar&gl=MA&ceid=MA%3Aar",
        "A",
        "middle_east",
    ),
    (
        "الشرق للأخبار",
        "https://news.google.com/rss/search?q=site%3Aasharq.com&hl=ar&gl=MA&ceid=MA%3Aar",
        "A",
        "middle_east",
    ),
    (
        "الشرق الأوسط",
        "https://news.google.com/rss/search?q=site%3Aaawsat.com&hl=ar&gl=MA&ceid=MA%3Aar",
        "A",
        "middle_east",
    ),
    (
        "العربي الجديد",
        "https://news.google.com/rss/search?q=site%3Aalaraby.co.uk&hl=ar&gl=MA&ceid=MA%3Aar",
        "B",
        "middle_east",
    ),

    # 🌐 العالم بالعربية
    (
        "القدس العربي",
        "https://news.google.com/rss/search?q=site%3Aalquds.co.uk&hl=ar&gl=MA&ceid=MA%3Aar",
        "B",
        "world_arabic",
    ),
    (
        "فرانس 24 عربي",
        "https://news.google.com/rss/search?q=site%3Afrance24.com+arabic&hl=ar&gl=MA&ceid=MA%3Aar",
        "A",
        "world_arabic",
    ),
    (
        "DW عربية",
        "https://news.google.com/rss/search?q=site%3Adw.com+arabic&hl=ar&gl=MA&ceid=MA%3Aar",
        "A",
        "world_arabic",
    ),
    (
        "BBC عربي",
        "https://news.google.com/rss/search?q=site%3Abbc.com+arabic&hl=ar&gl=MA&ceid=MA%3Aar",
        "A",
        "world_arabic",
    ),
    (
        "يورونيوز عربي",
        "https://news.google.com/rss/search?q=site%3Aeuronews.com+arabic&hl=ar&gl=MA&ceid=MA%3Aar",
        "B",
        "world_arabic",
    ),
    (
        "إندبندنت عربية",
        "https://news.google.com/rss/search?q=site%3Aindependentarabia.com&hl=ar&gl=MA&ceid=MA%3Aar",
        "B",
        "world_arabic",
    ),
    (
        "CNN بالعربية",
        "https://news.google.com/rss/search?q=site%3Aarabic.cnn.com&hl=ar&gl=MA&ceid=MA%3Aar",
        "A",
        "world_arabic",
    ),

    # 🔎 مصادر دولية للتحقق
    (
        "Reuters",
        "https://news.google.com/rss/search?q=site%3Areuters.com&hl=en&gl=US&ceid=US%3Aen",
        "A",
        "international",
    ),
    (
        "Associated Press",
        "https://news.google.com/rss/search?q=site%3Aapnews.com&hl=en&gl=US&ceid=US%3Aen",
        "A",
        "international",
    ),
]
